version: 2

models:
  - name: stg_customers
    description: Staged customer data with basic transformations
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - unique
          - not_null
      - name: full_name
        description: Concatenated first and last name

  - name: stg_orders
    description: Staged order data with basic transformations
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: amount
        description: Order amount in USD
        tests:
          - not_null

  - name: stg_products
    description: Staged product data with basic transformations
    columns:
      - name: product_id
        description: Primary key for products
        tests:
          - unique
          - not_null
      - name: product_name
        description: Name of the product
        tests:
          - not_null

